[programs.localnet]
qwestive_stake = "4UQ8dKxHjwV8QpetmqF62Xqnf17DavL3EWf6b6DbfYmz"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/sean/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
